/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as CallsDumpImport } from './routes/calls/dump';
import { Route as CallsDashboardImport } from './routes/calls/dashboard';
import { Route as CallsTrackingImport } from './routes/calls/tracking';

// Create Virtual Routes

const CallsIndexImport = createFileRoute('/calls')();

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const CallsIndexRoute = CallsIndexImport.update({
  path: '/calls',
  getParentRoute: () => rootRoute,
} as any);

const CallsDumpRoute = CallsDumpImport.update({
  path: '/calls/dump',
  getParentRoute: () => CallsIndexRoute,
} as any);

const CallsDashboardRoute = CallsDashboardImport.update({
  path: '/calls/dashboard',
  getParentRoute: () => CallsIndexRoute,
} as any);

const CallsTrackingRoute = CallsTrackingImport.update({
  path: '/calls/tracking',
  getParentRoute: () => CallsIndexRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/calls': {
      id: '/calls';
      path: '/calls';
      fullPath: '/calls';
      preLoaderRoute: typeof CallsIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/calls/dump': {
      id: '/calls/dump';
      path: '/dump';
      fullPath: '/calls/dump';
      preLoaderRoute: typeof CallsDumpImport;
      parentRoute: typeof CallsIndexImport;
    };
    '/calls/dashboard': {
      id: '/calls/dashboard';
      path: '/dashboard';
      fullPath: '/calls/dashboard';
      preLoaderRoute: typeof CallsDashboardImport;
      parentRoute: typeof CallsIndexImport;
    };
    '/calls/tracking': {
      id: '/calls/tracking';
      path: '/tracking';
      fullPath: '/calls/tracking';
      preLoaderRoute: typeof CallsTrackingImport;
      parentRoute: typeof CallsIndexImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CallsIndexRoute.addChildren([
    CallsDumpRoute,
    CallsDashboardRoute,
    CallsTrackingRoute,
  ]),
]);

/* prettier-ignore-end */
